name: Build latest (iOS)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ios
  cancel-in-progress: true

jobs:
  build:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - name: Compile iOS build
        id: compile
        run: |
          cd ios
          xcodebuild -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd build/Release-iphoneos
          mkdir Payload
          mv GoldenSparksCore.app Payload/GoldenSparksCore.app
          zip -r gsc.ipa Payload

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile GoldenSparks Core iOS build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ios/build/Release-iphoneos/gsc.ipa'
          DEST_NAME: 'GoldenSparks-Core.ipa'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled GoldenSparks Core iOS build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
